// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apicontainer

import (
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/api"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/api/acccountapi"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/api/guestapi"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/repository/db/accountrepo"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/repository/db/guestrepo"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/service/accountsvc"
	"github.com/flazhgrowth/baec-portfolio-api/internal/implementations/service/guestsvc"
	"github.com/flazhgrowth/fg-tamagochi/app"
)

// Injectors from container.go:

func InitAPI(app2 *app.App) *api.APIs {
	repository := accountrepo.New(app2)
	service := accountsvc.New(repository)
	accountAPI := accountapi.New(service)
	guestRepository := guestrepo.New(app2)
	guestService := guestsvc.New(guestRepository)
	guestAPI := guestapi.New(guestService)
	apIs := &api.APIs{
		AccountAPI: accountAPI,
		GuestAPI:   guestAPI,
	}
	return apIs
}
